### ISSUE TITLE
Extend local verification to ZkSync

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/airnode-protocol-v1#126]
from #124 

> One thing to note is that even though the hardhat-deploy implementation of zksync doesn't support it, it seems like we should be able to deploy the @api3/airnode-protocol-v1 contracts deterministically by calling ContractDeployer, which would mean that zksync testnet and mainnet contract addresses (and the proxy addresses) would be the same. However, this will cause the hardhat-etherscan implementation of zksync to not work, which is currently the only way of verifying our deployments (unless we extend our local verification, which would require zksync dependencies).

**Comment by bbenligiray** [comment]
I wouldn't bother tbh

**Comment by Ashar2shahid** [comment]
yeah, don't plan on doing it any time soon, still good to document it
