### ISSUE TITLE
Finalize repo QA compliance

### ISSUE THREAD

**Issue by BTT21000** [api3dao/airnode-protocol-v1#172]
As part of the TM issue https://github.com/api3dao/tasks/issues/849 for QA, some requirements need to be addressed:

### Repo setup requirements as per [new_repo_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_repo_creation_checklist.md):
- [ ] Write a short description for the repository in the description field
- [ ] Link to some relevant page if applicable (e.g. api3 docs, npm package link, ...)
- [ ] If/when applicable, create boards specific labels as applicable for issue tracking on specific API3 boards.
- [ ] If/when applicable, set up a project board (e.g. in the API3 project) for tracking tasks and progress.
- [ ] Add the relevant license file (LICENSE.md) consistent with the organizational standards or project requirements.
- [ ] Set up general Continuous Integration/Continuous Deployment (CI/CD) frameworks to automate testing and - in this case when applicable - deployment processes. This setup should include basic configurations applicable to any project within the organization.
- [ ] Install Renovate in the repository, following the guidelines outlined in [dependencyManagementStrategy.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/dependencyManagementStrategy.md).
- [ ] Create a renovate.json configuration file in the root of the repository to manage dependencies effectively, as per our dependency management strategy.
- [ ] Set up Renovate (or Dependabot or a similar tool) for automated security vulnerability scanning to detect vulnerabilities in the codebase.

### Package setup requirements as per [new_package_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_package_creation_checklist.md):
- [ ] Implement unit tests testing framework (e.g., Jest, Mocha).
- [ ] Configure Continuous Deployment (CD) for automated publishing to npm, tailored to the package's release and versioning strategy. This step can include setting up semantic versioning automation and npm publish commands.
- [ ] Add relevant package.json fields as applicable (e.g. such that repo links and - in this specific case - keywords show up in NPM, compare [this](https://www.npmjs.com/package/@material/button) to [this](https://www.npmjs.com/package/@api3/ois))
- [ ] Review the renovate.json configuration file to ensure it satisfies the package requirements and align with our dependency management strategy.
- [ ] Verify the setup of security vulnerability scanning tools (e.g. Renovate) for the codebase and dependencies.
- [ ] Define and document the release process and instructions, and the versioning strategy.
- [ ] Support GitHub Release (e.g. https://github.com/api3dao/chains/releases) as per our standard guidelines (tag releases, changesets such as these, changelogs, and release notes) and integrate CI/CD to support releases through GitHub as applicable.

**Comment by bbenligiray** [comment]
@BTT21000 I'm considering archiving this repo. The relevant contracts are moved to @api3/contracts, and the remaining contracts need significant changes before being used anywhere else. I can close this issue once this repo is archived.
