### ISSUE TITLE
Add external Multicall functionality

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode-protocol-v1#27]

**Comment by acenolaza** [comment]
@bbenligiray could you please add more info on this feature? Is this for adding a multicall contract that can be deployed separately?

**Comment by bbenligiray** [comment]
Sorry, I quickly noted this down on a call. I was thinking that Airnode was going to be able to need to use arbitrary contracts as authorizers, which may not inherit Multicall like our authorizers do. Then, we would need a multicall function that can make external calls (and it would be nice if AirnodeProtocol inherited this so we don't have to look for it). However, this no longer seems to be a requirement, so I'm closing the issue.
