### ISSUE TITLE
Rename templateId to be templateId/endpointId

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode-protocol-v1#35]
Full requests (in v0): Requests done with `endpointId` and `parameters`
Template requests (in v0): Requests done with `templateId` and `parameters`

In protocol v1, full requests are removed and template requests are plainly called requests. However, full requests were sometimes very useful. We can revive that feature at the protocol level by simply saying "requests can be made with `endpointId`s or `templateId`s". Since `templateId`s are a hash that is derived from an `endpointId`, there are no endpoints and templates with the same ID, which means such a request wouldn't be ambiguous.

When an Airnode receives a request it does the following:
- Check the endpoints and templates you know. If you know an endpoint with the ID, this is a full request so process it as such, and vice versa.
- If you don't know the ID, check the chain for templates with the ID. If it is there, this is a template request so process it as such.
- If none of the above worked, fail the request.

**Comment by bbenligiray** [comment]
The alternative is two different functions as before, but that both doubles all of our docs/examples/things a beginner needs to understand, and at the contract implementation it makes it not possible to switch between a full request and a template request without some additional implementation at the requester contract that normalizes the interface.

**Comment by andreogle** [comment]
Yeah it doesn't sound like it's worth the additional complexity and work

**Comment by bbenligiray** [comment]
templateId in the Subscription struct should also be endpointId/templateId
